import pygame
from constantes import *

# inicia assets 
def load_assets():
    assets = {}
    assets['background1']=pygame.image.load('assets/img/Entrada-p2-Insper.jpeg').convert()
    assets['background1'] = pygame.transform.scale(assets['background1'], (BACKGROUND_WIDTH, BACKGROUND_HEIGHT))
    assets['background2']=pygame.image.load('assets/img/sala.jpg').convert()
    assets['background2'] = pygame.transform.scale(assets['background2'], (BACKGROUND_WIDTH, BACKGROUND_HEIGHT))
    assets['background3']=pygame.image.load('assets/img/refeitorio-insper31.jpg').convert()
    assets['background3'] = pygame.transform.scale(assets['background3'], (BACKGROUND_WIDTH, BACKGROUND_HEIGHT))
    assets['humberto']=pygame.image.load('assets/img/SpriteHumberto.png').convert_alpha()
    assets['humberto'] = pygame.transform.scale(assets['humberto'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['floor'] = pygame.image.load('assets/img/floor.png').convert_alpha()
    assets['floor'] = pygame.transform.scale(assets['floor'], (FLOOR_WIDTH, FLOOR_HEIGHT))
    assets['atividade'] = pygame.image.load('assets/img/atividade.png').convert_alpha()
    assets['atividade'] = pygame.transform.scale(assets['atividade'], (ATIV_WIDTH, ATIV_HEIGHT))
    assets['humb_esq'] = pygame.image.load('assets/img/Humberto_esquerda.png').convert_alpha()
    assets['humb_esq'] = pygame.transform.scale(assets['humb_esq'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['humb_dir'] = pygame.image.load('assets/img/Humberto_direita.png').convert_alpha()
    assets['humb_dir'] = pygame.transform.scale(assets['humb_dir'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['aluno']=pygame.image.load('assets/img/aluno.png').convert_alpha()
    assets['aluno'] = pygame.transform.scale(assets['aluno'], (ALUNO_WIDTH, ALUNO_HEIGHT))
    assets['aluno_d']=pygame.image.load('assets/img/aluno_direita.png').convert_alpha()
    assets['aluno_d'] = pygame.transform.scale(assets['aluno_d'], (ALUNO_WIDTH, ALUNO_HEIGHT))
    assets['aluno_direita']=pygame.image.load('assets/img/Humberto_direita.png').convert_alpha()
    assets['humberto_cansado']=pygame.image.load('assets/img/Humberto_cansado.png').convert_alpha()
    assets['humberto_cansado'] = pygame.transform.scale(assets['humberto_cansado'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['humberto_exausto']=pygame.image.load('assets/img/Humberto_exausto.png').convert_alpha()
    assets['humberto_exausto'] = pygame.transform.scale(assets['humberto_exausto'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['humberto_morrendo']=pygame.image.load('assets/img/Humberto_morrendo.png').convert_alpha()
    assets['humberto_morrendo'] = pygame.transform.scale(assets['humberto_morrendo'], (HUMBERTO_HEIGHT, HUMBERTO_WIDTH))
    assets["score_font"] = pygame.font.Font('assets/img/Press_Start_2P/PressStart2P-Regular.ttf', 28)
    assets['humberto_morrendo'] = pygame.transform.scale(assets['humberto_morrendo'], (HUMBERTO_WIDTH, HUMBERTO_HEIGHT))
    assets['cafe']=pygame.image.load('assets/img/cafe.png').convert_alpha()
    assets['cafe'] = pygame.transform.scale(assets['cafe'], (CAFE_WIDTH, CAFE_HEIGHT))
    assets['coletando_exercicio']=pygame.mixer.Sound("assets/sdx/coletando exercicio.wav")
    assets["derrotado"]=pygame.mixer.Sound("assets/sdx/derrotado.wav")
    assets["inicialização_da_fase"]=pygame.mixer.Sound("assets/sdx/inicialização da fase.wav")
    assets["perde uma vida"]=pygame.mixer.Sound("assets/sdx/perde uma vida.wav")
    assets["pulo"]=pygame.mixer.Sound("assets/sdx/pulo.wav")
    assets["Trilha_sonora"]=pygame.mixer.Sound("assets/sdx/Trilha_sonora.wav")
    assets["Venceu_a_fase"]=pygame.mixer.Sound("assets/sdx/venceu a fase.wav")
    return assets