cenario_1fase = [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                           cx',
        '                         x   ',
        '     xxxa      x   a xxxa    ',
        'xxxx      xxxa  Ixxx         ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ]

cenario_2fase = [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '           x          xx     ',
        '        xx         xx        ',
        '     xxx        x            ',
        'xxxx        xxx              ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ]

cenario_3fase = [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '         xx        xx        ',
        '      xx         x           ',
        '    x          x             ',
        'xxx         xx        xx     ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ]