cenarios = {
    1: [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                            c',
        '                         a  x',
        '     aI             a  I x   ',
        '      xxx   a x I    xxx     ',
        'xxxx      xxx    xxx         ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ],
    2: [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                        a    ',
        '              a             c',
        '            x           I  xx',
        '      aI xx          a xx    ',
        '     xxx         I  x        ',
        'xxxx           xxx           ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ],
    3 : [
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '         I          I a      ',
        '     a   xx a   a  xx       c',
        '      xx         x      aI  x',
        '    x        I x         xx  ',
        'xxx         xx        xx     ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ],
    4: ['                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '               a             ',
        '                          c  ',
        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
    ]

}